# Linter github action

name: Super Linter
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Fetch directory
        run: "ls -a | echo"
